name: wood
description: "Wood E-commerce"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  firebase_auth_web: ^5.8.13
  cloud_firestore: ^5.6.11
  provider: ^6.1.1
  font_awesome_flutter: ^10.7.0
  image_picker:
  firebase_storage: